/*

1. Drag SVG Font file from FA zip file

2. Edit each icon's name based on its Unicode... 
   Copy keywords from FA 4.1.0 over to 4.3.0... 
   Keep logs and select matched icons

3. Manual edit of the remaining icons' keywords

?. How to manage the alias classes ?

*/

(function(){
    
    var $customFont = $('#custom_icons');
    var $iconsInFont = $('.font-custom_icons>li');
    var $oldFontAwesome = $('#fontawesome');
    
    // Massive search/replace made to build this list of unicodes
    // Alias were removed so every unicode should be unique
    var faVar = {};
    var injectFontAwesomeVars = function() {
        faVar['adjust'] = 'f042';
        faVar['adn'] = 'f170';
        faVar['align-center'] = 'f037';
        faVar['align-justify'] = 'f039';
        faVar['align-left'] = 'f036';
        faVar['align-right'] = 'f038';
        faVar['ambulance'] = 'f0f9';
        faVar['anchor'] = 'f13d';
        faVar['android'] = 'f17b';
        faVar['angellist'] = 'f209';
        faVar['angle-double-down'] = 'f103';
        faVar['angle-double-left'] = 'f100';
        faVar['angle-double-right'] = 'f101';
        faVar['angle-double-up'] = 'f102';
        faVar['angle-down'] = 'f107';
        faVar['angle-left'] = 'f104';
        faVar['angle-right'] = 'f105';
        faVar['angle-up'] = 'f106';
        faVar['apple'] = 'f179';
        faVar['archive'] = 'f187';
        faVar['area-chart'] = 'f1fe';
        faVar['arrow-circle-down'] = 'f0ab';
        faVar['arrow-circle-left'] = 'f0a8';
        faVar['arrow-circle-o-down'] = 'f01a';
        faVar['arrow-circle-o-left'] = 'f190';
        faVar['arrow-circle-o-right'] = 'f18e';
        faVar['arrow-circle-o-up'] = 'f01b';
        faVar['arrow-circle-right'] = 'f0a9';
        faVar['arrow-circle-up'] = 'f0aa';
        faVar['arrow-down'] = 'f063';
        faVar['arrow-left'] = 'f060';
        faVar['arrow-right'] = 'f061';
        faVar['arrow-up'] = 'f062';
        faVar['arrows'] = 'f047';
        faVar['arrows-alt'] = 'f0b2';
        faVar['arrows-h'] = 'f07e';
        faVar['arrows-v'] = 'f07d';
        faVar['asterisk'] = 'f069';
        faVar['at'] = 'f1fa';
        faVar['backward'] = 'f04a';
        faVar['ban'] = 'f05e';
        faVar['bar-chart'] = 'f080';
        faVar['barcode'] = 'f02a';
        faVar['bars'] = 'f0c9';
        faVar['bed'] = 'f236';
        faVar['beer'] = 'f0fc';
        faVar['behance'] = 'f1b4';
        faVar['behance-square'] = 'f1b5';
        faVar['bell'] = 'f0f3';
        faVar['bell-o'] = 'f0a2';
        faVar['bell-slash'] = 'f1f6';
        faVar['bell-slash-o'] = 'f1f7';
        faVar['bicycle'] = 'f206';
        faVar['binoculars'] = 'f1e5';
        faVar['birthday-cake'] = 'f1fd';
        faVar['bitbucket'] = 'f171';
        faVar['bitbucket-square'] = 'f172';
        faVar['bold'] = 'f032';
        faVar['bolt'] = 'f0e7';
        faVar['bomb'] = 'f1e2';
        faVar['book'] = 'f02d';
        faVar['bookmark'] = 'f02e';
        faVar['bookmark-o'] = 'f097';
        faVar['briefcase'] = 'f0b1';
        faVar['btc'] = 'f15a';
        faVar['bug'] = 'f188';
        faVar['building'] = 'f1ad';
        faVar['building-o'] = 'f0f7';
        faVar['bullhorn'] = 'f0a1';
        faVar['bullseye'] = 'f140';
        faVar['bus'] = 'f207';
        faVar['buysellads'] = 'f20d';
        faVar['calculator'] = 'f1ec';
        faVar['calendar'] = 'f073';
        faVar['calendar-o'] = 'f133';
        faVar['camera'] = 'f030';
        faVar['camera-retro'] = 'f083';
        faVar['car'] = 'f1b9';
        faVar['caret-down'] = 'f0d7';
        faVar['caret-left'] = 'f0d9';
        faVar['caret-right'] = 'f0da';
        faVar['caret-square-o-down'] = 'f150';
        faVar['caret-square-o-left'] = 'f191';
        faVar['caret-square-o-right'] = 'f152';
        faVar['caret-square-o-up'] = 'f151';
        faVar['caret-up'] = 'f0d8';
        faVar['cart-arrow-down'] = 'f218';
        faVar['cart-plus'] = 'f217';
        faVar['cc'] = 'f20a';
        faVar['cc-amex'] = 'f1f3';
        faVar['cc-discover'] = 'f1f2';
        faVar['cc-mastercard'] = 'f1f1';
        faVar['cc-paypal'] = 'f1f4';
        faVar['cc-stripe'] = 'f1f5';
        faVar['cc-visa'] = 'f1f0';
        faVar['certificate'] = 'f0a3';
        faVar['chain-broken'] = 'f127';
        faVar['check'] = 'f00c';
        faVar['check-circle'] = 'f058';
        faVar['check-circle-o'] = 'f05d';
        faVar['check-square'] = 'f14a';
        faVar['check-square-o'] = 'f046';
        faVar['chevron-circle-down'] = 'f13a';
        faVar['chevron-circle-left'] = 'f137';
        faVar['chevron-circle-right'] = 'f138';
        faVar['chevron-circle-up'] = 'f139';
        faVar['chevron-down'] = 'f078';
        faVar['chevron-left'] = 'f053';
        faVar['chevron-right'] = 'f054';
        faVar['chevron-up'] = 'f077';
        faVar['child'] = 'f1ae';
        faVar['circle'] = 'f111';
        faVar['circle-o'] = 'f10c';
        faVar['circle-o-notch'] = 'f1ce';
        faVar['circle-thin'] = 'f1db';
        faVar['clipboard'] = 'f0ea';
        faVar['clock-o'] = 'f017';
        faVar['cloud'] = 'f0c2';
        faVar['cloud-download'] = 'f0ed';
        faVar['cloud-upload'] = 'f0ee';
        faVar['code'] = 'f121';
        faVar['code-fork'] = 'f126';
        faVar['codepen'] = 'f1cb';
        faVar['coffee'] = 'f0f4';
        faVar['cog'] = 'f013';
        faVar['cogs'] = 'f085';
        faVar['columns'] = 'f0db';
        faVar['comment'] = 'f075';
        faVar['comment-o'] = 'f0e5';
        faVar['comments'] = 'f086';
        faVar['comments-o'] = 'f0e6';
        faVar['compass'] = 'f14e';
        faVar['compress'] = 'f066';
        faVar['connectdevelop'] = 'f20e';
        faVar['copyright'] = 'f1f9';
        faVar['credit-card'] = 'f09d';
        faVar['crop'] = 'f125';
        faVar['crosshairs'] = 'f05b';
        faVar['css3'] = 'f13c';
        faVar['cube'] = 'f1b2';
        faVar['cubes'] = 'f1b3';
        faVar['cutlery'] = 'f0f5';
        faVar['dashcube'] = 'f210';
        faVar['database'] = 'f1c0';
        faVar['delicious'] = 'f1a5';
        faVar['desktop'] = 'f108';
        faVar['deviantart'] = 'f1bd';
        faVar['diamond'] = 'f219';
        faVar['digg'] = 'f1a6';
        faVar['dot-circle-o'] = 'f192';
        faVar['download'] = 'f019';
        faVar['dribbble'] = 'f17d';
        faVar['dropbox'] = 'f16b';
        faVar['drupal'] = 'f1a9';
        faVar['eject'] = 'f052';
        faVar['ellipsis-h'] = 'f141';
        faVar['ellipsis-v'] = 'f142';
        faVar['empire'] = 'f1d1';
        faVar['envelope'] = 'f0e0';
        faVar['envelope-o'] = 'f003';
        faVar['envelope-square'] = 'f199';
        faVar['eraser'] = 'f12d';
        faVar['eur'] = 'f153';
        faVar['exchange'] = 'f0ec';
        faVar['exclamation'] = 'f12a';
        faVar['exclamation-circle'] = 'f06a';
        faVar['exclamation-triangle'] = 'f071';
        faVar['expand'] = 'f065';
        faVar['external-link'] = 'f08e';
        faVar['external-link-square'] = 'f14c';
        faVar['eye'] = 'f06e';
        faVar['eye-slash'] = 'f070';
        faVar['eyedropper'] = 'f1fb';
        faVar['facebook'] = 'f09a';
        faVar['facebook-official'] = 'f230';
        faVar['facebook-square'] = 'f082';
        faVar['fast-backward'] = 'f049';
        faVar['fast-forward'] = 'f050';
        faVar['fax'] = 'f1ac';
        faVar['female'] = 'f182';
        faVar['fighter-jet'] = 'f0fb';
        faVar['file'] = 'f15b';
        faVar['file-archive-o'] = 'f1c6';
        faVar['file-audio-o'] = 'f1c7';
        faVar['file-code-o'] = 'f1c9';
        faVar['file-excel-o'] = 'f1c3';
        faVar['file-image-o'] = 'f1c5';
        faVar['file-o'] = 'f016';
        faVar['file-pdf-o'] = 'f1c1';
        faVar['file-powerpoint-o'] = 'f1c4';
        faVar['file-text'] = 'f15c';
        faVar['file-text-o'] = 'f0f6';
        faVar['file-video-o'] = 'f1c8';
        faVar['file-word-o'] = 'f1c2';
        faVar['files-o'] = 'f0c5';
        faVar['film'] = 'f008';
        faVar['filter'] = 'f0b0';
        faVar['fire'] = 'f06d';
        faVar['fire-extinguisher'] = 'f134';
        faVar['flag'] = 'f024';
        faVar['flag-checkered'] = 'f11e';
        faVar['flag-o'] = 'f11d';
        faVar['flask'] = 'f0c3';
        faVar['flickr'] = 'f16e';
        faVar['floppy-o'] = 'f0c7';
        faVar['folder'] = 'f07b';
        faVar['folder-o'] = 'f114';
        faVar['folder-open'] = 'f07c';
        faVar['folder-open-o'] = 'f115';
        faVar['font'] = 'f031';
        faVar['forumbee'] = 'f211';
        faVar['forward'] = 'f04e';
        faVar['foursquare'] = 'f180';
        faVar['frown-o'] = 'f119';
        faVar['futbol-o'] = 'f1e3';
        faVar['gamepad'] = 'f11b';
        faVar['gavel'] = 'f0e3';
        faVar['gbp'] = 'f154';
        faVar['gift'] = 'f06b';
        faVar['git'] = 'f1d3';
        faVar['git-square'] = 'f1d2';
        faVar['github'] = 'f09b';
        faVar['github-alt'] = 'f113';
        faVar['github-square'] = 'f092';
        faVar['glass'] = 'f000';
        faVar['globe'] = 'f0ac';
        faVar['google'] = 'f1a0';
        faVar['google-plus'] = 'f0d5';
        faVar['google-plus-square'] = 'f0d4';
        faVar['google-wallet'] = 'f1ee';
        faVar['graduation-cap'] = 'f19d';
        faVar['gratipay'] = 'f184';
        faVar['h-square'] = 'f0fd';
        faVar['hacker-news'] = 'f1d4';
        faVar['hand-o-down'] = 'f0a7';
        faVar['hand-o-left'] = 'f0a5';
        faVar['hand-o-right'] = 'f0a4';
        faVar['hand-o-up'] = 'f0a6';
        faVar['hdd-o'] = 'f0a0';
        faVar['header'] = 'f1dc';
        faVar['headphones'] = 'f025';
        faVar['heart'] = 'f004';
        faVar['heart-o'] = 'f08a';
        faVar['heartbeat'] = 'f21e';
        faVar['history'] = 'f1da';
        faVar['home'] = 'f015';
        faVar['hospital-o'] = 'f0f8';
        faVar['html5'] = 'f13b';
        faVar['ils'] = 'f20b';
        faVar['inbox'] = 'f01c';
        faVar['indent'] = 'f03c';
        faVar['info'] = 'f129';
        faVar['info-circle'] = 'f05a';
        faVar['inr'] = 'f156';
        faVar['instagram'] = 'f16d';
        faVar['ioxhost'] = 'f208';
        faVar['italic'] = 'f033';
        faVar['joomla'] = 'f1aa';
        faVar['jpy'] = 'f157';
        faVar['jsfiddle'] = 'f1cc';
        faVar['key'] = 'f084';
        faVar['keyboard-o'] = 'f11c';
        faVar['krw'] = 'f159';
        faVar['language'] = 'f1ab';
        faVar['laptop'] = 'f109';
        faVar['lastfm'] = 'f202';
        faVar['lastfm-square'] = 'f203';
        faVar['leaf'] = 'f06c';
        faVar['leanpub'] = 'f212';
        faVar['lemon-o'] = 'f094';
        faVar['level-down'] = 'f149';
        faVar['level-up'] = 'f148';
        faVar['life-ring'] = 'f1cd';
        faVar['lightbulb-o'] = 'f0eb';
        faVar['line-chart'] = 'f201';
        faVar['link'] = 'f0c1';
        faVar['linkedin'] = 'f0e1';
        faVar['linkedin-square'] = 'f08c';
        faVar['linux'] = 'f17c';
        faVar['list'] = 'f03a';
        faVar['list-alt'] = 'f022';
        faVar['list-ol'] = 'f0cb';
        faVar['list-ul'] = 'f0ca';
        faVar['location-arrow'] = 'f124';
        faVar['lock'] = 'f023';
        faVar['long-arrow-down'] = 'f175';
        faVar['long-arrow-left'] = 'f177';
        faVar['long-arrow-right'] = 'f178';
        faVar['long-arrow-up'] = 'f176';
        faVar['magic'] = 'f0d0';
        faVar['magnet'] = 'f076';
        faVar['male'] = 'f183';
        faVar['map-marker'] = 'f041';
        faVar['mars'] = 'f222';
        faVar['mars-double'] = 'f227';
        faVar['mars-stroke'] = 'f229';
        faVar['mars-stroke-h'] = 'f22b';
        faVar['mars-stroke-v'] = 'f22a';
        faVar['maxcdn'] = 'f136';
        faVar['meanpath'] = 'f20c';
        faVar['medium'] = 'f23a';
        faVar['medkit'] = 'f0fa';
        faVar['meh-o'] = 'f11a';
        faVar['mercury'] = 'f223';
        faVar['microphone'] = 'f130';
        faVar['microphone-slash'] = 'f131';
        faVar['minus'] = 'f068';
        faVar['minus-circle'] = 'f056';
        faVar['minus-square'] = 'f146';
        faVar['minus-square-o'] = 'f147';
        faVar['mobile'] = 'f10b';
        faVar['money'] = 'f0d6';
        faVar['moon-o'] = 'f186';
        faVar['motorcycle'] = 'f21c';
        faVar['music'] = 'f001';
        faVar['neuter'] = 'f22c';
        faVar['newspaper-o'] = 'f1ea';
        faVar['openid'] = 'f19b';
        faVar['outdent'] = 'f03b';
        faVar['pagelines'] = 'f18c';
        faVar['paint-brush'] = 'f1fc';
        faVar['paper-plane'] = 'f1d8';
        faVar['paper-plane-o'] = 'f1d9';
        faVar['paperclip'] = 'f0c6';
        faVar['paragraph'] = 'f1dd';
        faVar['pause'] = 'f04c';
        faVar['paw'] = 'f1b0';
        faVar['paypal'] = 'f1ed';
        faVar['pencil'] = 'f040';
        faVar['pencil-square'] = 'f14b';
        faVar['pencil-square-o'] = 'f044';
        faVar['phone'] = 'f095';
        faVar['phone-square'] = 'f098';
        faVar['picture-o'] = 'f03e';
        faVar['pie-chart'] = 'f200';
        faVar['pied-piper'] = 'f1a7';
        faVar['pied-piper-alt'] = 'f1a8';
        faVar['pinterest'] = 'f0d2';
        faVar['pinterest-p'] = 'f231';
        faVar['pinterest-square'] = 'f0d3';
        faVar['plane'] = 'f072';
        faVar['play'] = 'f04b';
        faVar['play-circle'] = 'f144';
        faVar['play-circle-o'] = 'f01d';
        faVar['plug'] = 'f1e6';
        faVar['plus'] = 'f067';
        faVar['plus-circle'] = 'f055';
        faVar['plus-square'] = 'f0fe';
        faVar['plus-square-o'] = 'f196';
        faVar['power-off'] = 'f011';
        faVar['print'] = 'f02f';
        faVar['puzzle-piece'] = 'f12e';
        faVar['qq'] = 'f1d6';
        faVar['qrcode'] = 'f029';
        faVar['question'] = 'f128';
        faVar['question-circle'] = 'f059';
        faVar['quote-left'] = 'f10d';
        faVar['quote-right'] = 'f10e';
        faVar['random'] = 'f074';
        faVar['rebel'] = 'f1d0';
        faVar['recycle'] = 'f1b8';
        faVar['reddit'] = 'f1a1';
        faVar['reddit-square'] = 'f1a2';
        faVar['refresh'] = 'f021';
        faVar['renren'] = 'f18b';
        faVar['repeat'] = 'f01e';
        faVar['reply'] = 'f112';
        faVar['reply-all'] = 'f122';
        faVar['retweet'] = 'f079';
        faVar['road'] = 'f018';
        faVar['rocket'] = 'f135';
        faVar['rss'] = 'f09e';
        faVar['rss-square'] = 'f143';
        faVar['rub'] = 'f158';
        faVar['scissors'] = 'f0c4';
        faVar['search'] = 'f002';
        faVar['search-minus'] = 'f010';
        faVar['search-plus'] = 'f00e';
        faVar['sellsy'] = 'f213';
        faVar['server'] = 'f233';
        faVar['share'] = 'f064';
        faVar['share-alt'] = 'f1e0';
        faVar['share-alt-square'] = 'f1e1';
        faVar['share-square'] = 'f14d';
        faVar['share-square-o'] = 'f045';
        faVar['shield'] = 'f132';
        faVar['ship'] = 'f21a';
        faVar['shirtsinbulk'] = 'f214';
        faVar['shopping-cart'] = 'f07a';
        faVar['sign-in'] = 'f090';
        faVar['sign-out'] = 'f08b';
        faVar['signal'] = 'f012';
        faVar['simplybuilt'] = 'f215';
        faVar['sitemap'] = 'f0e8';
        faVar['skyatlas'] = 'f216';
        faVar['skype'] = 'f17e';
        faVar['slack'] = 'f198';
        faVar['sliders'] = 'f1de';
        faVar['slideshare'] = 'f1e7';
        faVar['smile-o'] = 'f118';
        faVar['sort'] = 'f0dc';
        faVar['sort-alpha-asc'] = 'f15d';
        faVar['sort-alpha-desc'] = 'f15e';
        faVar['sort-amount-asc'] = 'f160';
        faVar['sort-amount-desc'] = 'f161';
        faVar['sort-asc'] = 'f0de';
        faVar['sort-desc'] = 'f0dd';
        faVar['sort-numeric-asc'] = 'f162';
        faVar['sort-numeric-desc'] = 'f163';
        faVar['soundcloud'] = 'f1be';
        faVar['space-shuttle'] = 'f197';
        faVar['spinner'] = 'f110';
        faVar['spoon'] = 'f1b1';
        faVar['spotify'] = 'f1bc';
        faVar['square'] = 'f0c8';
        faVar['square-o'] = 'f096';
        faVar['stack-exchange'] = 'f18d';
        faVar['stack-overflow'] = 'f16c';
        faVar['star'] = 'f005';
        faVar['star-half'] = 'f089';
        faVar['star-half-o'] = 'f123';
        faVar['star-o'] = 'f006';
        faVar['steam'] = 'f1b6';
        faVar['steam-square'] = 'f1b7';
        faVar['step-backward'] = 'f048';
        faVar['step-forward'] = 'f051';
        faVar['stethoscope'] = 'f0f1';
        faVar['stop'] = 'f04d';
        faVar['street-view'] = 'f21d';
        faVar['strikethrough'] = 'f0cc';
        faVar['stumbleupon'] = 'f1a4';
        faVar['stumbleupon-circle'] = 'f1a3';
        faVar['subscript'] = 'f12c';
        faVar['subway'] = 'f239';
        faVar['suitcase'] = 'f0f2';
        faVar['sun-o'] = 'f185';
        faVar['superscript'] = 'f12b';
        faVar['table'] = 'f0ce';
        faVar['tablet'] = 'f10a';
        faVar['tachometer'] = 'f0e4';
        faVar['tag'] = 'f02b';
        faVar['tags'] = 'f02c';
        faVar['tasks'] = 'f0ae';
        faVar['taxi'] = 'f1ba';
        faVar['tencent-weibo'] = 'f1d5';
        faVar['terminal'] = 'f120';
        faVar['text-height'] = 'f034';
        faVar['text-width'] = 'f035';
        faVar['th'] = 'f00a';
        faVar['th-large'] = 'f009';
        faVar['th-list'] = 'f00b';
        faVar['thumb-tack'] = 'f08d';
        faVar['thumbs-down'] = 'f165';
        faVar['thumbs-o-down'] = 'f088';
        faVar['thumbs-o-up'] = 'f087';
        faVar['thumbs-up'] = 'f164';
        faVar['ticket'] = 'f145';
        faVar['times'] = 'f00d';
        faVar['times-circle'] = 'f057';
        faVar['times-circle-o'] = 'f05c';
        faVar['tint'] = 'f043';
        faVar['toggle-off'] = 'f204';
        faVar['toggle-on'] = 'f205';
        faVar['train'] = 'f238';
        faVar['transgender'] = 'f224';
        faVar['transgender-alt'] = 'f225';
        faVar['trash'] = 'f1f8';
        faVar['trash-o'] = 'f014';
        faVar['tree'] = 'f1bb';
        faVar['trello'] = 'f181';
        faVar['trophy'] = 'f091';
        faVar['truck'] = 'f0d1';
        faVar['try'] = 'f195';
        faVar['tty'] = 'f1e4';
        faVar['tumblr'] = 'f173';
        faVar['tumblr-square'] = 'f174';
        faVar['twitch'] = 'f1e8';
        faVar['twitter'] = 'f099';
        faVar['twitter-square'] = 'f081';
        faVar['umbrella'] = 'f0e9';
        faVar['underline'] = 'f0cd';
        faVar['undo'] = 'f0e2';
        faVar['university'] = 'f19c';
        faVar['unlock'] = 'f09c';
        faVar['unlock-alt'] = 'f13e';
        faVar['upload'] = 'f093';
        faVar['usd'] = 'f155';
        faVar['user'] = 'f007';
        faVar['user-md'] = 'f0f0';
        faVar['user-plus'] = 'f234';
        faVar['user-secret'] = 'f21b';
        faVar['user-times'] = 'f235';
        faVar['users'] = 'f0c0';
        faVar['venus'] = 'f221';
        faVar['venus-double'] = 'f226';
        faVar['venus-mars'] = 'f228';
        faVar['viacoin'] = 'f237';
        faVar['video-camera'] = 'f03d';
        faVar['vimeo-square'] = 'f194';
        faVar['vine'] = 'f1ca';
        faVar['vk'] = 'f189';
        faVar['volume-down'] = 'f027';
        faVar['volume-off'] = 'f026';
        faVar['volume-up'] = 'f028';
        faVar['weibo'] = 'f18a';
        faVar['weixin'] = 'f1d7';
        faVar['whatsapp'] = 'f232';
        faVar['wheelchair'] = 'f193';
        faVar['wifi'] = 'f1eb';
        faVar['windows'] = 'f17a';
        faVar['wordpress'] = 'f19a';
        faVar['wrench'] = 'f0ad';
        faVar['xing'] = 'f168';
        faVar['xing-square'] = 'f169';
        faVar['yahoo'] = 'f19e';
        faVar['yelp'] = 'f1e9';
        faVar['youtube'] = 'f167';
        faVar['youtube-play'] = 'f16a';
        faVar['youtube-square'] = 'f166';
    };
    injectFontAwesomeVars();

    
    var parseNextIcon =  function() {
        var total = $iconsInFont.length;
        if (idx < total) {
            var $this = $($iconsInFont.get(idx));
            $('.icon-edit', $this).click();
            $this.one('fma:edit-modal-available', setIconProperties);
            setTimeout(function(){$this.trigger('fma:edit-modal-available');}, 1000);
        }
    };
    
    var setIconProperties =  function(evt) {
        var $this = $(evt.target);
        
        // Unicode
        var $unicode = $('#gopt__code');
        
        // Form
        var $form = $unicode.closest('form');
        
        // Name
        var $nameFld = $('#gopt__css_name', $form);
        var iconName = getNameFromUnicode($unicode.val().toLowerCase());
        $nameFld.val(iconName);
        
        // Keywords
        var $keywordsFld = $('#gopt__keywords', $form);
        //$keywordsFld.val('name-num-'+idx);
        var $matchedIcon = $('li[title^="name: \''+iconName+'\'"]', $oldFontAwesome);
        if ($matchedIcon.length) {
            // Copy keywords
            var title = "name: 'thumbs-up',   tags: thumbs, vote, up, like, love";
            var title = $matchedIcon.attr('title');
            var title_arr = title.split('tags: ');
            $keywordsFld.val(title_arr[1]);
        } else {
            // Default
            $keywordsFld.val(iconName);
            $this.css('background', 'yellow');
        }
        
        // Save!
        var $saveBtn = $('[data-on-click="cmd:glyph_options.save"]', $form);
        $saveBtn.click();
        $this.one('fma:edit-modal-saved', selectIcon);
        setTimeout(function(){$this.trigger('fma:edit-modal-saved');}, 500);
    };
    
    var getNameFromUnicode =  function(unicode) {
        for (var key in faVar) {
            if (unicode==faVar[key]) {
                return key;
            }
        }
        return '';
    };
    
    var selectIcon =  function(evt) {
        var $this = $(evt.target);
        $('.selector__glyph-inner', $this).click();
        setTimeout(function(){
            idx++;
            parseNextIcon();
        }, 500);
    };
    
    // Start parsing
    var idx = 0;
    parseNextIcon();
})();
